### ISSUE TITLE
Create documentation (model.html)

### ISSUE THREAD

**Issue by HawesDomingue** [marshallgallatin/cs373-idb#11]
Run pydoc3 on models.py, which will create models.html [make models.html], that then documents the interfaces to your functions.
Create inline comments if you need to explain the why of a particular implementation.
Use a consistent coding convention with good variable names, good indentation, blank lines, and blank spaces (see Google Python Style Guide).

**Comment by marshallgallatin** [comment]
We had to use pydoc since pydoc3 doesn't like sqlalchemy
https://github.com/marshallgallatin/cs373-idb/blob/master/models.html
