### ISSUE TITLE
Document RESTful API using Apiary (apiary.apib)

### ISSUE THREAD

**Issue by HawesDomingue** [marshallgallatin/cs373-idb#13]
Document a RESTful API using Apiary.
Log into Apiary with your GitHub credentials and connect Apiary to the repo.
Think carefully about the types and format of the requests and responses.

**Comment by HawesDomingue** [comment]
https://app.apiary.io/restipe/editor

**Comment by marshallgallatin** [comment]
http://docs.restipe.apiary.io/#
https://github.com/marshallgallatin/cs373-idb/blob/master/apiary.apib
